# Generated by Django 4.1 on 2022-09-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="totalhours",
            field=models.IntegerField(default=36),
            preserve_default=False,
        ),
    ]
