# Generated by Django 4.1 on 2022-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_course_totalhours"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="hours_per_day",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
