# Generated by Django 4.1 on 2022-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendance"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="student",),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ManyToManyField(to="attendance.student"),
        ),
    ]
