# Generated by Django 4.1 on 2022-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remove_attendance_student_attendance_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="course",),
        migrations.RemoveField(model_name="attendance", name="student",),
        migrations.AddField(
            model_name="attendance",
            name="course_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="student_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="absent_hours",
            field=models.IntegerField(blank=True),
        ),
    ]
