# Generated by Django 4.1 on 2022-10-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_alter_attendance_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="course_id",),
        migrations.RemoveField(model_name="attendance", name="student_id",),
        migrations.AddField(
            model_name="attendance",
            name="course",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.student",
            ),
            preserve_default=False,
        ),
    ]
