# Generated by Django 4.1 on 2022-10-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_remove_attendance_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="classes",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.class",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.course"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.student"
            ),
        ),
    ]
