# Generated by Django 4.1 on 2022-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_attendance_classes_alter_attendance_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="absent_hours", field=models.IntegerField(),
        ),
    ]
