# Generated by Django 4.1 on 2022-10-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_alter_attendance_absent_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_rate",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
